service_desc/helpdesc/urls.py
from django.urls import path,include

from .views import RequestCreate,RequestList,RequestUpdate,CommentCreate,StatusUpdate,RequestDetail,ResolutionUpdate,\
    EventList
from rest_framework.routers import DefaultRouter
from .views import RequestViewSet


router = DefaultRouter()
router.register(r'api/request', RequestViewSet)

urlpatterns = [
    path('', RequestList.as_view(), name='request_list_url'),
    path('request_create/',  RequestCreate.as_view(), name='request_create_url'),
    path('request_update/<int:pk>/',  RequestUpdate.as_view(), name='request_update_url'),
    path('request_detail/<int:pk>/',  RequestDetail.as_view(), name='request_detail_url'),
    path('comment_create/',  CommentCreate.as_view(), name='comment_create_url'),
    path('status_update/<int:pk>/',StatusUpdate.as_view(),name='status_update_url'),
    path('resolution_update/<int:pk>/',ResolutionUpdate.as_view(),name='resolution_update_url'),
    path('resolution_update/<int:pk>/',ResolutionUpdate.as_view(),name='resolution_update_url'),
    path('event_list/',EventList.as_view(),name='event_list_url'),
    path('', include(router.urls)),

]

service_desc/service_desc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helpdesc.urls')),
    path('authorisation/', include('autorization.urls')),

]

service_desc/helpdesc/models.py
from django.db import models
from django.contrib.auth.models import User


class Request(models.Model):
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=50)
    info = models.TextField(null=True,blank=True)
    date_create = models.DateTimeField(auto_now_add=True)
    date_last_update = models.DateTimeField(auto_now_add=True)
    PRIORITY_CHOICES = [
        ('1', 'Low'),
        ('2', 'Medium'),
        ('3', 'High')
    ]
    priority = models.CharField(choices=PRIORITY_CHOICES,max_length=2,default='1')
    STATUS_CHOICES = [
        ('1', 'New'),
        ('2', 'In Progress'),
        ('3', 'Done'),
        ('4', 'Restored')
    ]
    status = models.CharField(choices=STATUS_CHOICES,max_length=2,default='1')
    RESOLUTION_CHOICES = [
        ('1', 'Resolved'),
        ('2', 'Rejected')
    ]
    resolution = models.CharField(choices=RESOLUTION_CHOICES,max_length=2,null=True,blank=True)
    flag_delete = models.BooleanField(default=False)
    flag_reopen = models.BooleanField(default=False)


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    request = models.ForeignKey(Request,on_delete=models.CASCADE,default='')
    text = models.CharField(max_length=200)
    date_comment = models.DateTimeField(auto_now_add=True)


class Event(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    request = models.ForeignKey(Request, on_delete=models.DO_NOTHING,related_name='request_name')
    EVENT_CHOICES = [
        ('1', 'Create Request'),
        ('2', 'Update Request'),
        ('3', 'Create Comment'),
        ('4', 'Update Comment'),
        ('5', 'Update Status')
    ]
    event = models.CharField(choices=EVENT_CHOICES, max_length=2, default='1')
    event_date_time = models.DateTimeField(auto_now_add=True)

    def create_event(user,request,event,event_date_time):
        event = Event.objects.create(user=user, request=request, event=event,event_date_time=event_date_time)
        event.save()

service_desc/helpdesc/forms.py
from django.forms import ModelForm, HiddenInput
from .models import Request, Comment


class RequestCreateForm(ModelForm):
    class Meta:
        model = Request
        fields = ('name', 'info', 'priority')


class CommentCreateForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class StatusUpdateForm(ModelForm):
    class Meta:
        model = Request
        fields = ('status',)
        widgets = {'status': HiddenInput()}

class ResolutionUpdateForm(ModelForm):
    class Meta:
        model = Request
        fields = ('resolution',)
        widgets = {'resolution': HiddenInput()}

service_desc/helpdesc/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from .models import Request, Comment, Event
from .forms import RequestCreateForm, CommentCreateForm, StatusUpdateForm, ResolutionUpdateForm
from django.utils import timezone
from rest_framework.viewsets import ModelViewSet
from .api.serializers import RequestSerializer
from rest_framework.pagination import PageNumberPagination


class RequestList(ListView, LoginRequiredMixin):
    model = Request
    paginate_by = 100
    ordering = ['-priority', '-date_last_update']

    def get_queryset(self):
        queryset = super().get_queryset()
        status = str(self.request.GET.get('status_resolution')).lower()
        if self.request.user.is_authenticated:
            if self.request.user.is_staff:
                if status in ['1', '2', '3', '4']:
                    queryset = queryset.filter(status=status)
            else:
                queryset = queryset.filter(user=self.request.user).filter(flag_delete=False)
        return queryset

    def get_template_names(self):
        if self.request.user.is_staff:
            return ['helpdesc/admin_panel.html']
        return ['helpdesc/index.html']


class RequestCreate(LoginRequiredMixin, CreateView):
    model = Request
    success_url = '/'
    form_class = RequestCreateForm
    template_name = 'helpdesc/request_create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        Event.create_event(self.object.user, self.object, '1', timezone.now())
        return super().form_valid(form)


class RequestUpdate(LoginRequiredMixin, UpdateView):
    model = Request
    form_class = RequestCreateForm
    template_name = 'helpdesc/request_update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = self.object.comment_set.all()
        context.update({
            'comments': comments,
            'comment_create_form': CommentCreateForm,
            'status_update_form': StatusUpdateForm
        })
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.date_last_update = timezone.now()
        self.object.save()
        Event.create_event(self.object.user, self.object, '1', timezone.now())
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('request_detail_url', kwargs={'pk': self.object.pk})


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    http_method_names = ['post']
    form_class = CommentCreateForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.request = Request.objects.get(pk=self.request.POST.get("request"))
        Event.create_event(self.object.user, self.object.request, '3', timezone.now())
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('request_detail_url', kwargs={'pk': self.object.request.pk})


class StatusUpdate(LoginRequiredMixin, UpdateView):
    model = Request
    http_method_names = ['post']
    success_url = '/'
    form_class = StatusUpdateForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.date_last_update = timezone.now()
        self.object.status = self.request.POST.get("status_resolution", "1")
        if self.object.status == "4":
            self.object.flag_reopen = True
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('request_detail_url', kwargs={'pk': self.object.pk})


class ResolutionUpdate(LoginRequiredMixin, UpdateView):
    model = Request
    http_method_names = ['post']
    success_url = '/'
    form_class = ResolutionUpdateForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.date_last_update = timezone.now()
        self.object.status = "3"
        self.object.resolution = self.request.POST.get("request_resolution")
        if self.object.flag_reopen and self.object.resolution == "2":
            self.object.flag_delete = True
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('request_detail_url', kwargs={'pk': self.object.pk})


class RequestDetail(LoginRequiredMixin, DetailView):
    model = Request
    success_url = '/'
    template_name = 'helpdesc/request_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = self.object.comment_set.all()
        context.update({
            'comments': comments,
            'comment_create_form': CommentCreateForm,
            'status_update_form': StatusUpdateForm,
            'resolution_update_form': ResolutionUpdateForm
        })
        return context


class EventList(LoginRequiredMixin, ListView):
    model = Event
    paginate_by = 10
    success_url = '/'
    template_name = 'helpdesc/event_list.html'


class StandardResultsSetPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'
    max_page_size = 100


class RequestViewSet(ModelViewSet):
    queryset = Request.objects.all()
    serializer_class = RequestSerializer
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):
        qs = super().get_queryset()
        priority = str(self.request.query_params.get('priority')).lower()
        if priority in ['1', '2', '3']:
            return qs.filter(priority=priority)
        return qs

service_desc/templates/helpdesc/admin_panel.html
{% extends 'base.html' %}

{% block content  %}
<div class="row">
    <div class="col-lg-8 ml-5 mt-3 ">
        <nav class="nav nav-pills flex-column flex-sm-row">
            <form method="get">
                <input type="hidden" name="status_resolution" value="4">
                <button type="submit" class="flex-sm-fill text-sm-center nav-link active">Restored</button>
            </form>
            <form method="get">
                <input type="hidden" name="status_resolution" value="1">
                <button type="submit" class="flex-sm-fill text-sm-center nav-link active">New</button>
            </form>
            <form method="get">
                <input type="hidden" name="status_resolution" value="2">
                <button type="submit" class="flex-sm-fill text-sm-center nav-link active">In Progress</button>
            </form>
            <form method="get">
                <input type="hidden" name="status_resolution" value="3">
                <button type="submit" class="flex-sm-fill text-sm-center nav-link active">Done</button>
            </form>
        </nav>
        {% for request in object_list %}
        <div class="card mt-1">
            <div class="card-header">
                {{request.name}}
            </div>
            <div class="card-body">
                <div class="row">
                    <h3>{{request.user.first_name}} {{request.user.last_name}}</h3>
                    {% if request.status == "3" %}
                    <button type="button" class="btn btn-success ml-auto">{{request.get_status_display}}
                    </button>
                    {% else %}
                    <button type="button" class="btn btn-warning ml-auto">{{request.get_status_display}}
                    </button>
                    {% endif %}
                </div>
                <p>{{request.date_create|date:"D, d M, Y"}}</p>
                <p class="card-text">{{request.info|truncatewords:30}}</p>
                <a class="btn btn-primary" href="{% url 'request_detail_url' request.pk %}">Detail</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

service_desc/templates/helpdesc/event_list.html
{% block content  %}
<div class="card" style="width: 18rem;">
    <div class="card-header">
        Events
    </div>
    <ul class="list-group list-group-flush">
        {% for event in object_list %}
        <li class="list-group-item">
            <p>{{event.user.username}} {{event.get_event_display}} {{event.request.name}} at {{event.event_date_time}}</p>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

service_desc/templates/helpdesc/index.html
{% extends 'base.html' %}

{% block content  %}
<div class="row">
    <div class="col-lg-3 ml-5 mt-3">
        <h5>New</h5>
        {% for request in object_list %}
        {% if request.status == "1" or request.status == "4" %}

        <div class="card bg-light mb-3" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ request.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ request.user.username }}</h6>
                <p class="card-text">{{ request.info|truncatewords:10 }}</p>
                <a class="request" href="{% url 'request_detail_url' request.pk %}">Detail</a>
            </div>
        </div>

        {% endif %}
        {% endfor %}
    </div>
    <div class="col-lg-3 ml-5 mt-3">
        <h5>In Progress</h5>
        {% for request in object_list %}
        {% if request.status == "2" %}
        <div class="card bg-light mb-3" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ request.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ request.user.username }}</h6>
                <p class="card-text">{{ request.info|truncatewords:10 }}</p>
                <a class="request" href="{% url 'request_detail_url' request.pk %}">Detail</a>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="col-lg-3 ml-5 mt-3">
        <h5>Done</h5>
        {% for request in object_list %}
        {% if request.status == "3" %}
        <div class="card bg-light mb-3" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ request.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ request.user.username }}</h6>
                <p class="card-text">{{ request.info|truncatewords:10 }}</p>
                <a class="request" href="{% url 'request_detail_url' request.pk %}">Detail</a>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

service_desc/templates/helpdesc/request_create.html
{% extends 'base.html' %}

{% block content  %}
<div class="row">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
    </form>
</div>
{% endblock %}

service_desc/templates/helpdesc/request_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content  %}
<div class="row justify-content-center mt-5">
    <div class="col-md-8">
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">{{object.name}}</h1>
                <hr class="my-4">
                <div class="row mt-5">
                    <div class="col">
                        <h5>Priority: {{object.get_priority_display}}</h5>
                        <h5>Status: {{object.get_status_display}}</h5>
                        {% if object.resolution %}
                        <div class="row mt-2">
                            <div class="col order-12">
                                <h5>Resolution: {{object.get_resolution_display}}</h5>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                        {% if user.is_staff %}
                        <div class="row mt-2 ml-auto">
                            {% if object.status == "1" %}
                            <form method="post" action="{% url 'status_update_url' object.pk %}">
                                {% csrf_token %}
                                {{ status_update_form|crispy }}
                                <input type="hidden" name="status_resolution" value="2">
                                <button type="submit" class="btn btn-success">Start Progress</button>
                            </form>
                            {% endif %}
                             {% if object.status == "1" or object.status == "2"  %}
                            <form method="post" action="{% url 'resolution_update_url' object.pk %}">
                                {% csrf_token %}
                                {{ resolution_update_form|crispy }}
                                <input type="hidden" name="request_resolution"
                                       value="1">
                                <button type="submit" class="btn btn-success">Resolve</button>
                            </form>
                            <form method="post" action="{% url 'resolution_update_url' object.pk %}">
                                {% csrf_token %}
                                {{ resolution_update_form|crispy }}
                                <input type="hidden" name="request_resolution"
                                       value="2">
                                <button type="submit" class="btn btn-success">Reject</button>
                            </form>
                            {% endif %}
                        </div>
                        {% endif %}
                    {% if not user.is_staff %}
                    {% if object.status == "3" and object.resolution == "2" %}
                    <form method="post" action="{% url 'status_update_url' object.pk %}">
                        {% csrf_token %}
                        {{ status_update_form|crispy }}
                        <input type="hidden" name="status_resolution" value="4">
                        <button type="submit" class="btn btn-success">Reopen</button>
                    </form>
                    {% endif %}
                    {% endif %}
                </div>
                <div class="container content-row">
                    <div class="row mt-5">
                        <div class="col ml-0">
                            <div class="card h-200">
                                <div class="card-body">
                                    <p>{{object.info}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mt-5">
                     <div class="col ml-auto">
                    <p>{{object.date_create|date:"D, d M, Y"}}</p>
                     </div>
                </div>
                <div class="row">
                    <div class="col ml-auto">
                        <p>{{object.date_last_update|date:"D, d M, Y"}}</p>
                    </div>
                </div>
                {% if not user.is_staff %}
                <div class="row mt-5">
                    <a class="btn btn-success" href="{% url 'request_update_url' object.pk %}" role="button">Update</a>
                </div>
                {% endif %}
                <div class="row mt-5"></div>
                {% for comment in comments %}
                <div class="card mt-2">
                    <div class="card-body">
                        <div class="title h5">
                            <a href="#"><b>{{ comment.user }}</b></a>
                            added a comment.
                            <h6 class="text-muted time">{{comment.date_comment|date:"D, d M, Y"}}</h6>
                        </div>
                        <p>{{ comment.text }}</p>
                    </div>
                </div>
                {% endfor %}
                {%if object.status == "2" %}
                <form action="{% url 'comment_create_url' %}" method="post">
                    {% csrf_token %}
                    {{ comment_create_form|crispy }}
                    <input type="hidden" value="{{ object.pk }}" name="request">
                    <button type="submit" class="btn btn-success">Send</button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

service_desc/templates/helpdesc/request_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content  %}
<div class="row justify-content-center">
    <div class="col-md-6">
        {% if not user.is_staff %}
        <form action="{% url 'request_update_url' object.pk%}" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-success">Save</button>
        </form>
        {% else %}
        <form action="{% url 'status_update_url' object.pk %}" method="post">
            {% csrf_token %}
            {{ status_update_form|crispy }}
            <button type="submit" class="btn btn-success">Save</button>
        </form>
        {% endif %}
        {% for comment in comments %}
        <div class="card">
            <div class="card-body">
                <div class="title h5">
                    <a href="#"><b>{{ comment.user }}</b></a>
                    added a comment.
                    <h6 class="text-muted time">{{comment.date_comment|date:"D, d M, Y"}}</h6>
                </div>
                <p>{{ comment.text }}</p>
            </div>
        </div>
        {% endfor %}
        {%if object.status == "2" %}
        <form action="{% url 'comment_create_url' %}" method="post">
            {% csrf_token %}
            {{ comment_create_form|crispy }}
            <input type="hidden" value="{{ object.pk }}" name="request">
            <button type="submit" class="btn btn-success">Send</button>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}